[package]
name = "mozjs_sys"
description = "System crate for the Mozilla SpiderMonkey JavaScript engine."
repository = "https://github.com/servo/mozjs/"
version = "0.0.0"
authors = ["Mozilla"]
links = "mozjs"
build = "build.rs"
license = "MPL-2.0"

[features]
debugmozjs = []
promises = []

[lib]
name = "mozjs_sys"
path = "lib.rs"

[dependencies]
libc = "0.2"
libz-sys = "1.0"
