[workspace]
members = ["wasmer-winter"]
resolver = "2"

[workspace.package]
repository = "https://github.com/wasmerio/wasmer-winter/"
license = "MIT"
edition = "2021"

[workspace.dependencies]
libc = "=0.2.139"

[patch.crates-io]
