name: Patch Integrity

on: 
  push:
    branches-ignore: "master"
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps on linux
      run: |
        sudo apt install jq -y
    - name: Get mozjs
      run: |
        ./get_mozjs.sh
    - name: Apply patch
      run: |
        python3 ./etc/update.py --no-commit mozjs.tar.xz
    - name: Compare
      run: |
        git diff --no-ext-diff --quiet --exit-code